logging:
  level:
    ru.yandex.practicum.infra.gateway: INFO
    org:
      springframework: INFO

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**, /categories/**,
              /admin/compilations/**, /compilations/**,
              /admin/events/**, /users/{userId}/events, /users/{userId}/events/{eventId}, /events/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests/**
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**, /users/{userId}/comments/**, /comments/**
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: stats_service_route
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**

server:
  port: 8080